### ISSUE TITLE
Use of pyxdg

### ISSUE THREAD

**Issue by Yamakaky** [jceb/dex#14]
Why do you implement your own .desktop parser ? You should use [pyxdg](http://freedesktop.org/wiki/Software/pyxdg/) for that.

**Comment by jceb** [comment]
Hm, what I don't like about pyxdg is the additional dependency.  The source code is not significantly simplified to justify this step.  The main advantage I see is the improved compatibility.  Issues like #28 would probably be a thing of the past.  However, I don't think these are major issues.  At the moment I'm not convinced yet.
