### ISSUE TITLE
Terminal=true issue.

### ISSUE THREAD

**Issue by goodmind** [jceb/dex#27]
Hello,

```dex``` doesn't creating new terminal emulator window instead it's open app in current terminal.

If there is no terminal ```.desktop``` will started, but doesn't appear.

I doesn't have ```x-terminal-emulator```, can you provide option for this?

**Comment by jceb** [comment]
Thanks for reporting the issue.  At the moment I don't have time to look into the issue.  Maybe you could try to look for yourself - it's just a little Python script.
