### ISSUE TITLE
desktop file with Type=Service is ignored as empty

### ISSUE THREAD

**Issue by Konfekt** [jceb/dex#28]
If the desktop file, for example baloo_file.desktop, contains 
```
Type=Service
```
then
```
dex -dva -e KDE gives
```
Ignoring empty file: baloo_file.desktop
```

**Comment by kyrias** [comment]
`Type=Service` is not one of the 3 allowed types of desktop entries defined in the Desktop Entry Specification.

**Comment by kyrias** [comment]
And the specification also says to ignore desktop entries with unknown types, so this is working as intended.

**Comment by Konfekt** [comment]
Thanks for clarifying. 

This leaves me wondering: How does KDE treat it? There's in `/etc/xdg/autostart` a file `baloo_file.desktop` that reads
```
[Desktop Entry]
Type=Service
Exec=baloo_file
X-KDE-StartupNotify=false
X-KDE-autostart-condition=baloofilerc:Basic Settings:Enabled:true
X-KDE-autostart-phase=0
X-GNOME-Autostart-enabled=true
OnlyShowIn=KDE;GNOME;Unity;XFCE
NoDisplay=true
```
and is started at start up of KDE. Seems as supposedly (`OnlyShowIn=KDE;GNOME;Unity;XFCE
`) also in other DEs.

**Comment by kyrias** [comment]
https://techbase.kde.org/Development/Tutorials/Desktop_File#Menus seems to imply that `Type=Service` is used for context menu items, hmm.

**Comment by jceb** [comment]
Hm, I guess it should be supported then.  Pull requests anyone?

**Comment by kyrias** [comment]
If it's used by context menu items it doesn't make much sense for `dex` to execute them IMO.  Though I guess if you specify a full path it would be okay.

**Comment by jceb** [comment]
I implemented it quickly.  Since the baloo file was in the autostart directory I figured that it's probably more than just a menu entry.  Have a look here: https://cgit.freedesktop.org/xdg/pyxdg/tree/xdg/DesktopEntry.py#n215

**Comment by Konfekt** [comment]
Does not work: With the single baloo_file.desktop file in ` $XDG_CONFIG_HOME/autostart/kde`, 
```sh
dex --environment KDE --autostart --search-paths $XDG_CONFIG_HOME/autostart/kde -d
```
gives an empty output (and of course, neither starts it without `-d`).

**Comment by jceb** [comment]
I get the following error

```% dex test.desktop
Execution faild: test.desktop
"'/home/jceb/Documents/Projects/dex/test.desktop' is not a valid Desktop Entry because Type or Name keys are missing."
```

with this file:
```[Desktop Entry]
Type=Service
Exec=baloo_file
X-KDE-StartupNotify=false
X-KDE-autostart-condition=baloofilerc:Basic Settings:Enabled:true
X-KDE-autostart-phase=0
X-GNOME-Autostart-enabled=true
OnlyShowIn=KDE;GNOME;Unity;XFCE
NoDisplay=true
```

Do you get the same error?  In my case `Name` is missing.

I allowed Name to be missing for Type=Service entries.

**Comment by Konfekt** [comment]
I  am sorry. A git rebase must have overwritten the dex symlink in PATH with a copy of dex. Now that the latest version is symlinked, it works fine.
