### ISSUE TITLE
Add example to associate dex with .Desktop files

### ISSUE THREAD

**Issue by stuaxo** [jceb/dex#29]
Dex solved an issue I've had for the longest time -

- Clicking on .desktop files opened them in gedit.

I made a desktop file that launches dex, and with that my desktop is useful again.

```$ dex -c `which dex` -t ~/.local/share/applications/```

or to install globally

```$ sudo dex -c `which dex` -t /usr/local/share/applications/```

This has been doing my head in for years (and others judging by bugzilla), so may be worth including in the README as an example.

**Comment by jceb** [comment]
Thanks for the idea. I'm happy to receive a pull request.

**Comment by stuaxo** [comment]
I need to spend some time to read this ticket for nautilus to see if this is still needed -
https://gitlab.gnome.org/GNOME/nautilus/issues/443

**Comment by legluondunet** [comment]
@stuaxo 
thank you for this tips, and don't forget to add this entry:
application/x-desktop=dex.desktop;
in .local/usr/share/applications/mimeapps.list 
for only user space or for all users in:
/usr/share/applications/defaults.list
@jceb Big thanks for Dex

**Comment by jceb** [comment]
I'll close this issue because of inactivity. Feel free to open it again with a PR.
