### ISSUE TITLE
Optional Type and Name entry keys

### ISSUE THREAD

**Issue by sgtpep** [jceb/dex#30]
Maybe it would sound silly. I've used to generate .desktop files from scripts the most minimal way:
```
 cat > ~/.config/autostart/foo.desktop << EOF
[Desktop Entry]
Exec=foo
EOF 
```
It have been working on all desktop environments so far (openbox via openbox-xdg-autostart, unity, mate, etc.)

I'm aware that Type and Name entry keys are required according to the freedesktop specification, but it looks like most of implementation consider them optional. It makes sense to be forgiving to user errors (like html5) or ignorance.

**Comment by jceb** [comment]
Agreed.  I'd be happy to accept a pull request.

**Comment by jceb** [comment]
No pull request received - closing this issue.
