### ISSUE TITLE
Search desktop files ?

### ISSUE THREAD

**Issue by stuaxo** [jceb/dex#40]
It would be great if dex provided a search function.

Currently I've got a couple of versions of TIlix installed on my computer, one works, one doesn't.
Would be great if I could use dex to tell me which desktop files had that app in them, and some other info.

**Comment by ildar** [comment]
> grep -R -i TIlix /usr/share/applications/

?

**Comment by stuaxo** [comment]
Cheers - it turns out I needed to check $XDG_DATA_DIRS since it was a flatpak.
