### ISSUE TITLE
Error with Chrome: Failed to connect to the bus: Could not parse server address: Unknown address type

### ISSUE THREAD

**Issue by unformatt** [jceb/dex#42]
Despite the error, Chrome seems to launch OK. However, about 1 of every 10 launches silently fail and I don't know if this is related.

Seems to be related to `LD_LIBRARY_PATH`. My `LD_LIBRARY_PATH` is not set. Is dex somehow setting an `LD_LIBRARY_PATH` before is launches a .desktop file?

https://unix.stackexchange.com/questions/423198/google-chrome-starts-but-fails-to-open-https-websites-this-site-can-t-be-reach/470360#470360

Full Error:

```
2031:2127:0125/112625.776052:ERROR:bus.cc(396)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
Gkr-Message: couldn't connect to dbus session bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[2031:2031:0125/112625.857561:ERROR:x11_input_method_context_impl_gtk.cc(144)] Not implemented reached in virtual void libgtkui::X11InputMethodContextImplGtk::SetSurroundingText(const base::string16 &, const gfx::Range &)

(google-chrome:2031): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Unknown or unsupported transport 'disabled' for address 'disabled:'
```

**Comment by jceb** [comment]
Hm, no, dex doesn't set `LD_LIBRARY_PATH`. I'm afraid the issue comes from somewhere else.
