### ISSUE TITLE
Option to exclude specific desktop files

### ISSUE THREAD

**Issue by marcopaganini** [jceb/dex#43]
I use i3 as my main window manager and dex to autostart my desktop files. Most of these files are installed in `/etc/xdg/autostart` by their respective packages and everything works as expected.

Unfortunately, given the nature of Gnome & Friends, I also have to start all required daemons (in my case, cinnamon-settings-demon which is now split into a bunch of executables and desktop files). Dex does a great job with that, but:

1. Some of the desktop files in `/etc/xdg/autostart` are also started by the session-manager (ex: pasystray). Those can be disabled on the cinnamon settings page (which controls the session daemon).

1. Some of the desktop files are started by the display manager (and I honestly can't find out where, exactly). In my particular case, lightdm starts nm-applet and when I use `dex -a`, I end up with two nm-applets.

I'm willing to add a "--exclude" option to dex to treat those special cases. In my case, I could run with `dex -a --exclude nm-applet` to prevent nm-applet from starting up (despite -a).

Thoughts?

**Comment by jceb** [comment]
Yes, it's tricky to figure out these issues. I'd like to avoid the exclude option to keep `dex` simple. As a quick workaround you can provide empty files in `~/.config/autostart` that prevent `dex` from running any file with that name. `dex -a -v -d` lists everything that would be started automatically by it. Maybe this helps you to find the trouble makers.

**Comment by jceb** [comment]
Nothing to be done here at the moment.
