### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by jluttine** [jceb/dex#50]
Hi, thanks for dex, it's amazing! Do you have any plans to make a new release? In distros, typically releases are packaged, and there are a few nice new features after the latest release. I can of course just package the latest commit, but it'd be nice to package it with a proper version number and know that the author considers it stable enough for a release.

**Comment by jceb** [comment]
Hi @jluttine, thanks for the interest. I just created a new release. Please notice that I personally moved away from dex and replaced it with systemd. The whole explanation is in the readme.
