### ISSUE TITLE
Running individual autostart entries via systemd

### ISSUE THREAD

**Issue by WhyNotHugo** [jceb/dex#55]
Hi! I've been thinking a bit about dex+systemd integration, and I've a kind-of-proposal, but would like to hear your thoughts before hacking into it. The idea is basically:

- Ship a `dex@.service` file which has something like `ExecStart=/usr/bin/dex run %I`.
- `dex run $NAME` will merely run `$NAME.desktop`. Just one entry though, not all of them.
- A user can run `systemctl --user enable dex@someapp.service`.

Note that `dex run` is very very similar to `dex -w`, but takes only the basename instead of the full path (e.g.: `caffeine` instead of  `/etc/xdg/autostart/caffeine.desktop`).

The end result is being able to run autostart-desktop entries with three benefits:

- Entries must be explicitly enabled by the user (the XDG spec is highly flawed IMHO in that applications decide if they autostart, not the user).
- They run as a systemd service, so get managed/restarted properly and all that. I personally have a statusbar indicator if any service transitions into a failed state.
- There's no need to re-write autostart desktop entries as systemd-services

As a bonus point, something like `dex enable $NAME` that runs `systemctl --user enable dex@$NAME.service` might be interesting, though this _is_ a bit systemd-centric, and, so far, it seems that `dex` is very systemd-agnostic, which is probably important for a lot of users.

What are you thoughts on this?

**Comment by jceb** [comment]
Interesting idea, I like it. Desktop Entries are tedious to manage because programs just add them. Therefore, I wonder how practical the approach is to manage each service individually. Personally, I use the following `dex.service`:

```ini
[Unit]
Description=Desktop Autostart

[Service]
ExecStart=dex -a -e XFCE
Type=forking
RemainAfterExit=yes

[Install]
WantedBy=graphical-session.target
```

It starts all services for the XFCE environment. This is close enough and not starts the GNOME and KDE services.

Feel free to develop the services.

**Comment by stuaxo** [comment]
If there is `dex run` there should be a way of listing these basenames, e.g. `dex ls` or `dex list`

**Comment by Konfekt** [comment]
> It starts all services for the XFCE environment. This is close enough and not starts the GNOME and KDE services.

Would this service also automatically restart each autostart entry on failure, like an individual systemd service of a single autostart entry does (by default)?

**Comment by jceb** [comment]
> If there is `dex run` there should be a way of listing these basenames, e.g. `dex ls` or `dex list`

This is not super straight forward since there's not one fixed set of basenames. The way I determine the available basenames is via `dex -a --dry-run`. Is a separate subcommand still makes sense, please open a separate issue.

**Comment by Konfekt** [comment]
Thank you, that's how I've been handling it, using systemd services for background processes without graphical indicator. So an advantage of @WhyNotHugo 's `dex run` is that it includes a tray icon to indicate any failed service:

> They run as a systemd service, so get managed/restarted properly and all that. I personally have a statusbar indicator if any service transitions into a failed state
