### ISSUE TITLE
dex -a - only start applications that have not been launched yet

### ISSUE THREAD

**Issue by arcolinuxz** [jceb/dex#58]
Is it possible to tell it to ONLY launch applications in .config/autostart that have not been started yet?

This video will make things more clear.

https://youtu.be/55bYkTlbxaY

In TWM (dusk fork from dwm) it is annoying that all these windows pop open again and again.

**Comment by jceb** [comment]
Nope, that's not possible because dex doesn't keep track of what has been started. If you need that feature, I recommend migrating to a systemd-based workflow as described here: https://github.com/jceb/dex#autostart-alternative.
