### ISSUE TITLE
Support for the XDG_CURRENT_DESKTOP environment variable

### ISSUE THREAD

**Issue by adrian-amaglio** [jceb/dex#59]
First, thanks a lot for your work !

I was using two windows managers lately and I found out that dex was executing the same services on both.
After some investigations, I think it is because the XDG_CURRENT_DESKTOP variable is not used out of the box.
I am now using `dex -e "$XDG_CURRENT_DESKTOP"` for this to work.

As dex is relying on XDG variables, it would be coherent to read XDG_CURRENT_DESKTOP. Maybe as a default value for args.environment ?

What do you think about it ?

**Comment by jceb** [comment]
Sounds good to me. Feel free to create a PR for it 👍
