### ISSUE TITLE
Fails to execute double quoted command

### ISSUE THREAD

**Issue by akinokonomi** [jceb/dex#67]
The desktop entry with following `Exec=` key
```desktop
Exec=sh -c "notify-send date \\"\\$(date)\\""
```

fails to execute with error
```py
Execution faild: test.desktop
'Exec value contains an unbalanced number of quote characters.'
```

Replacing double quotes with single fixes the error, but this entry is not valid.
```desktop
Exec=sh -c 'notify-send date \\"\\$(date)\\"'
```

Version
dex 0.9.0
Python 3.11.3

**Comment by jceb** [comment]
Hm, well, I'd say write a script that does the job and put the script in `Exec=`. Quotes are a mess.

**Comment by tucho** [comment]
What if the .desktop file is not ours to meddle with?

**Comment by jceb** [comment]
@tucho well, at the moment there's not much that can be done. The best path forward would be to prepare a PR.

**Comment by stuaxo** [comment]
Having some example .desktop files to run tests against might be the worst thing (especially ones with edge cases).
