### ISSUE TITLE
`dex -c /etc/xdg/autostart/my-app.desktop` creates a `.desktop.desktop` file in ~/.config/autostart

### ISSUE THREAD

**Issue by martisj** [jceb/dex#68]
```
❯ dex --version
dex 0.9.0

❯ uname --all
Linux thinkbook 6.4.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 03 Aug 2023 16:02:01 +0000 x86_64 GNU/Linux
```

I would expect the creation to keep the "single" `.desktop` file extension. Or maybe I am just using the command incorrectly?

This is what I run:
```
❯ dex -c /etc/xdg/autostart/welcome.desktop

~/.config/autostart
❯ exa --oneline --icons --classify
 albert.desktop -> /usr/share/applications/albert.desktop
 firewall-applet.desktop*
 picom.desktop
 redshift-gtk.desktop
 shutter.desktop
 wallpaper-once.desktop
 welcome.desktop.desktop
```

**Comment by jceb** [comment]
Hi, please check out the examples: https://github.com/jceb/dex#examples

`dex -c` is meant to be used with the executable that you want to create a `.desktop` file for. Calling it on a `.desktop` file would create a `.desktop` file that would executed the former `.desktop` file. That won't work.
