### ISSUE TITLE
dex fails to run emacsclient on archlinux

### ISSUE THREAD

**Issue by sunng87** [jceb/dex#73]
```
$ dex /usr/share/applications/emacsclient.desktop 
Execution faild: /usr/share/applications/emacsclient.desktop
'Exec value contains an unbalanced number of quote characters.'
```

The emacsclient.desktop file:
https://github.com/emacs-mirror/emacs/blob/master/etc/emacsclient.desktop#L6

**Comment by jceb** [comment]
Could you put the command in a script and just call it from the desktop file?
